name: rickmortyapp
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.0.0-411.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  # No usar shared_preference (no es seguro)
  flutter_secure_storage: ^6.0.0
  provider: ^6.0.5
  equatable: ^2.0.5
  # Para la generar codigo
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  cached_network_image: ^3.2.3
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  # Para la generar codigo
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  freezed: ^2.4.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
