name: cupertinoapp
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  websafe_svg: ^1.1.0
  after_layout: ^1.0.7+2
  image_picker: ^0.6.3+4
  shared_preferences: ^0.5.8
  http: ^0.12.2
  equatable: ^1.2.2
  bloc:
  flutter_bloc:
  cached_network_image: ^2.2.0+1
  shimmer:
  flutter_youtube: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
