name: authapp
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.10.6
  firebase_auth: ^3.3.4
  flutter_meedu: ^5.2.1
  freezed: ^1.1.1
  freezed_annotation: ^1.1.0
  shared_preferences: ^2.0.13
  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/light/
    - assets/images/dark/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
