name: cine_clean_riverpod
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.0-128.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  go_router: ^10.1.2
  # Para la lectura del archivo .env
  flutter_dotenv: ^5.1.0
  dio: ^5.3.2
  flutter_riverpod: ^2.4.0
  card_swiper: ^3.0.1
  animate_do: ^3.1.2
  # Para el formato de fechas y otrso objetos
  intl: ^0.18.1
  # Para BD local
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  # Para BD local
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
  #   - images/a_dot_burr.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
